## Append samples you want in your CSV to this file as resources ##
resources:
- nnf_v1alpha7_nnfaccess.yaml
- nnf_v1alpha7_nnfcontainerprofile.yaml
- nnf_v1alpha7_nnfdatamovement.yaml
- nnf_v1alpha7_nnfdatamovementmanager.yaml
- nnf_v1alpha7_nnfdatamovementprofile.yaml
- nnf_v1alpha7_nnflustremgt.yaml
- nnf_v1alpha7_nnfnode.yaml
- nnf_v1alpha7_nnfnodeblockstorage.yaml
- nnf_v1alpha7_nnfnodeecdata.yaml
- nnf_v1alpha7_nnfnodestorage.yaml
- nnf_v1alpha7_nnfportmanager.yaml
- nnf_v1alpha7_nnfstorage.yaml
- nnf_v1alpha7_nnfstorageprofile.yaml
- nnf_v1alpha7_nnfsystemstorage.yaml
- nnf_v1alpha8_nnfaccess.yaml
- nnf_v1alpha8_nnfcontainerprofile.yaml
- nnf_v1alpha8_nnfdatamovement.yaml
- nnf_v1alpha8_nnfdatamovementmanager.yaml
- nnf_v1alpha8_nnfdatamovementprofile.yaml
- nnf_v1alpha8_nnflustremgt.yaml
- nnf_v1alpha8_nnfnode.yaml
- nnf_v1alpha8_nnfnodeblockstorage.yaml
- nnf_v1alpha8_nnfnodeecdata.yaml
- nnf_v1alpha8_nnfnodestorage.yaml
- nnf_v1alpha8_nnfportmanager.yaml
- nnf_v1alpha8_nnfstorage.yaml
- nnf_v1alpha8_nnfstorageprofile.yaml
- nnf_v1alpha8_nnfsystemstorage.yaml
- nnf_v1alpha9_nnfaccess.yaml
- nnf_v1alpha9_nnfcontainerprofile.yaml
- nnf_v1alpha9_nnfdatamovement.yaml
- nnf_v1alpha9_nnfdatamovementmanager.yaml
- nnf_v1alpha9_nnfdatamovementprofile.yaml
- nnf_v1alpha9_nnflustremgt.yaml
- nnf_v1alpha9_nnfnode.yaml
- nnf_v1alpha9_nnfnodeblockstorage.yaml
- nnf_v1alpha9_nnfnodeecdata.yaml
- nnf_v1alpha9_nnfnodestorage.yaml
- nnf_v1alpha9_nnfportmanager.yaml
- nnf_v1alpha9_nnfstorage.yaml
- nnf_v1alpha9_nnfstorageprofile.yaml
- nnf_v1alpha9_nnfsystemstorage.yaml
- nnf_v1alpha10_nnfaccess.yaml
- nnf_v1alpha10_nnfcontainerprofile.yaml
- nnf_v1alpha10_nnfdatamovement.yaml
- nnf_v1alpha10_nnfdatamovementmanager.yaml
- nnf_v1alpha10_nnfdatamovementprofile.yaml
- nnf_v1alpha10_nnflustremgt.yaml
- nnf_v1alpha10_nnfnode.yaml
- nnf_v1alpha10_nnfnodeblockstorage.yaml
- nnf_v1alpha10_nnfnodeecdata.yaml
- nnf_v1alpha10_nnfnodestorage.yaml
- nnf_v1alpha10_nnfportmanager.yaml
- nnf_v1alpha10_nnfstorage.yaml
- nnf_v1alpha10_nnfstorageprofile.yaml
- nnf_v1alpha10_nnfsystemstorage.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
